server:
  port: 8761
eureka:
  instance:
    #eureka server通讯地址
    hostname: eureka
    #显示在注册中心的微服务名称
    instance-id: eureka
    #是否显示IP地址
    prefer-ip-address: true
    #client发送心跳间隔时间 默认30s
    lease-renewal-interval-in-seconds: 30
    #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到次心跳，则将移除该instance
    lease-expiration-duration-in-seconds: 90
  client:
    #是否提取服务端注册信息
    fetch-registry: false
    #是否注册自己
    register-with-eureka: false
  server:
    #自我保护机制
    enable-self-preservation: true
    #eureka server清理无效节点的时间间隔，默认60000毫秒
    eviction-interval-timer-in-ms: 60000
